service: my-service-name
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:*"
      Resource: "*"
functions:
  openaiToken:
    handler: backend/aws/index.handler
    events:
      - http:
          method: get
          path: openai/token
